### ISSUE TITLE
Add params as label qualifier

### ISSUE THREAD

**Issue by ben-manes** [jzillmann/gradle-jmh-report#2]
Thanks for this plugin! I was using jmh-charts, which had this same [problem](https://github.com/nilskp/jmh-charts/issues/1).

In benchmarks that use `@Param` the labels should qualify what is being tested. Otherwise the chart is not clear. See for example [ComputeBenchmark](https://github.com/ben-manes/caffeine/blob/master/caffeine/src/jmh/java/com/github/benmanes/caffeine/cache/ComputeBenchmark.java) which produces the chart below.

![image](https://cloud.githubusercontent.com/assets/378614/23097018/3ddfea40-f5de-11e6-9d12-f883a1093427.png)

In `jmh-charts` that would look something like,
![image](https://cloud.githubusercontent.com/assets/378614/23097045/2763616a-f5df-11e6-8d69-6143f1ae208a.png)

**Comment by jzillmann** [comment]
Thanks @ben-manes. Supporting params is on my near term list!

**Comment by jzillmann** [comment]
@ben-manes I didn't fix it in the gradle plugin yet, but in the online visualizer: http://jmh.morethan.io
Looks like this:

<img width="939" alt="computebenchmark" src="https://cloud.githubusercontent.com/assets/148472/25063160/5e7326d4-21dd-11e7-8707-3ed92cfec288.png">

The plan to make use of that visualizer in the next version of the gradle plugin. So any feedback on it will flow into the gradle plugin as well!

**Comment by ben-manes** [comment]
That looks very nice, thanks!

Perhaps the param value(s) should be bold and the bars given a different color? Alternatively, it might look nicer if showing the param name was optional and just the value(s) was the item's label. Then group by method with the name on the outer bracket, e.g. a nested y-label.

The thrpt ops/s could be the x-label and the chart title the benchmark name. Also the x values could be shortened with a magnitude label, e.g. 35M, 70M, ...

I think those changes would declutter the chart and make items standout more.

**Comment by jzillmann** [comment]
Does that match your expectation ?
<img width="957" alt="computebenchmarkv2" src="https://cloud.githubusercontent.com/assets/148472/25170396/ae463b5a-24ea-11e7-94c7-283356c30246.png">

**Comment by ben-manes** [comment]
That's great. Can add a label and use short numerical values on the x axis?

**Comment by jzillmann** [comment]
For the x-axis tick shortening i created a separate issue: https://github.com/jzillmann/jmh-visualizer/issues/2

What you mean by 
> add a label 

?

**Comment by ben-manes** [comment]
The benchmark type, e.g. throughput

**Comment by jzillmann** [comment]
Ok, i pushed a new version online (http://jmh.morethan.io).
Your caffeine suite now looks much better i think since it was using params heavily....

Not sure if you can decipher that, but FYI, this is how i'm handling the params:

0. no param => standard
1. one param, single method => convert to (0)
2. one param, multi methods => Bar per param Value
3. two params, single methods => convert to (2)
4. two+ params, multi methods => combine params & convert to (2)
5. three+ params, single methods => combine params & convert to (0)

If you have any more requests one the online tool, please use https://github.com/jzillmann/jmh-visualizer/issues.

Once i brought the online version into the gradle plugin, i will close this issue...

**Comment by ben-manes** [comment]
Thanks!

**Comment by jzillmann** [comment]
This is now released as 0.2.0!

**Comment by ben-manes** [comment]
Thanks!
