### ISSUE TITLE
jmhReport configuration cannot deal with JMH' default JSON file name and jmhReportOutput seems to be superfluous in the current implementation

### ISSUE THREAD

**Issue by loxal** [jzillmann/gradle-jmh-report#5]
I am not using the JMH Gradle plugin because it's (1) currently broken on Windows (2) is a superfluous layer of indirection that not really provide any additional value and (3) does not work with (at least) Kotlin. 

Hence I am using vanilla JMH which works just fine without any JMH plugin and creates a `jmh-result.json` file in the projects root which I reconfigured to be put in `build/jmh-results.json`. 

However this plugins seems to have problems with a dash inside the **default file name** which is `jmh-result.json` and creates a broken report when I use `jmhResultPath = project.file("build/jmh-result.json")`. 

Also it seems like `jmhReportOutput` must point to a folder that contains the JSON results file and cannot be just any folder under `build/`.

**Comment by jzillmann** [comment]
@loxal Thanks for trying at least! :)

So a few things...
- (1) Yeah didn't look into Windows builds... if you have a patch or more information on what is not working... appreciated!
- (2) The plugin does not feature the execution of JMH benchmarks.. It just generates a html report on an existing json result file. Users of the plugin are expected to have a already working JMH execution setup (since there are multiple ways on how to do that, e.g see https://blog.morethan.io/jmh-with-gradle-from-easy-to-simple-dc872d57cf7f)
- (3) Not sure if the Kotlin problem is based on (2). If not, let me know what is the problem!
- You are right, the '-' creates a problem in the report. Thanks for reporting, is just released 0.6.2.1 with a fix for this!
- I didn't have any problems with changing the jmhReportDir to the 'build' dir. If you still have, i would require more information!
